### ISSUE TITLE
Overriding default handlers

### ISSUE THREAD

**Issue by gigablah** [husobee/vestigo#13]
Is there a way to override the default handlers (e.g. `notFoundHandler`) with a custom one?

**Comment by husobee** [comment]
Not currently.  I think we should probably add a helper function to set those on router initialization if specified.  I will start working on a branch to give you access to change the default base handlers.

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/14 <- this is what i would suggest doing.  Do you feel the need to override all of the default handlers?  If so there might be more involved, as methodNotAllowedHandler and others actually take in parameters which are used in a closure.  Thoughts?

**Comment by gigablah** [comment]
Ah, that would do nicely. Probably no need for anything too complex for now.

**Comment by husobee** [comment]
Okay, will merge this in.

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/14 <- merged.  Closing this issue.
