### ISSUE TITLE
routing bug

### ISSUE THREAD

**Issue by donseba** [husobee/vestigo#15]
Hi, 

While testing the package I found an bug : 

```
router := vestigo.NewRouter()
router.Get("/a/a", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("found : a "))
	})
router.Get("/a/b", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("found : b "))
	}))
router.Get("/a/:bb",  func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("cannot find bb ")) 
	}))

log.Fatal(http.ListenAndServe("localhost:1234", router))
```
if i navigate to `/a/a` and `a/b` it works okay. navigating to `a/bb` is not possible though .

Hope it can be fixed. looks pretty neat. :+1:

**Comment by husobee** [comment]
@donseba: Thank you for submitting this issue.  This is the same problem as here: https://github.com/husobee/vestigo/issues/8

Could you please check out the branch "check-sib" to see if that will work for you?  I tested it on your example above and it seems to work.  I am planning on merging that branch today if it works for you.

**Comment by donseba** [comment]
Thanks for the prompt reply, I will try it in the morning and let you know.

**Comment by donseba** [comment]
Hello I just checked the "check-sib" branch and it fixed the issue :) good job!

**Comment by husobee** [comment]
@donseba: great.  will get a PR ready with this fix.

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/16 has been merged. This bug should be resolved.

**Comment by donseba** [comment]
I can confirm that it fixed the problem!
