### ISSUE TITLE
Add import "time"

### ISSUE THREAD

**Issue by hanneslehmann** [husobee/vestigo#19]
While trying your code I got

```bash
./main.go:21: undefined: time in time.Second
```

Solved this by including/importing the time package

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/20 should correct the readme.  Will merge after it builds.  Thanks.

**Comment by husobee** [comment]
Merged.  Thanks again, please feel free to close the issue if this resolves it.

**Comment by hanneslehmann** [comment]
Thanks & regards
