### ISSUE TITLE
routing bug - route ignored

### ISSUE THREAD

**Issue by shasderias** [husobee/vestigo#21]
```
package main

import (
	"fmt"
	"net/http"

	"github.com/husobee/vestigo"
)

func main() {
	r := vestigo.NewRouter()

	r.Get("/test", testHandler)
	r.Get("/test/:id", testGetHandler)
	r.Get("/test/list/:abc", testListHandler)

	http.ListenAndServe(":9999", r)
}

func testHandler(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "testHandler")
}

func testGetHandler(w http.ResponseWriter, r *http.Request) {
	id := vestigo.Param(r, "id")
	fmt.Fprintln(w, "id:", id)
}

func testListHandler(w http.ResponseWriter, r *http.Request) {
	abc := vestigo.Param(r, "abc")
	fmt.Fprintln(w, "abc:", abc)
}
```

Given the above program, the routes "/test/123" and "/test/list/123" are both handled by testGetHandler. Shouldn't "/test/list/123" be handled by testListHandler (or at least 404ed).

Removing the line: 	r.Get("/test/list/:abc", testListHandler) causes the route "/test/list/123" to 404.

go version go1.6.2 windows/amd64
vestigo version 7aafc8cfe1bfaf7bfc9a083a112cc1b56b7dc219

**Comment by husobee** [comment]
@shasderias I think I have found what is causing this issue.  This is an artifact from https://github.com/husobee/vestigo/issues/8 where the "last ditch" effort to match a url parameter was happening slightly before it was supposed to.  This pull request should fix it: https://github.com/husobee/vestigo/pull/22  Let me know if you have more issues.

**Comment by shasderias** [comment]
Works like a charm, thank you :)

Thank you for the library as well!

**Comment by husobee** [comment]
Good. Will create some unit tests and merge the pull request tonight. Thanks.

**Comment by husobee** [comment]
@shasderias: Okay, all merged up. Please feel free to close.  Thanks!

**Comment by shasderias** [comment]
thanks very much!
