### ISSUE TITLE
Add documentation for pprof

### ISSUE THREAD

**Issue by josephspurrier** [husobee/vestigo#26]
Great router! Thanks for the taking the time to build it and I enjoyed reading your article about the issues with many of the popular routers. I was using httprouter and encountered some of the issues you mentioned, but feel your router would be a great addition to my project, https://github.com/blue-jay/blueprint.

Here is something you could add to your documentation on how to access pprof via URL: http://localhost/debug/pprof/

```go
// Load the routes.
func Load() {
	// Enable Pprof
	router.Get("/debug/pprof/", Index)
	router.Get("/debug/pprof/:pprof", Profile)
}

// Index shows the profile index.
func Index(w http.ResponseWriter, r *http.Request) {
	pprof.Index(w, r)
}

// Profile shows the individual profiles.
func Profile(w http.ResponseWriter, r *http.Request) {
	switch vestigo.Param(r, "pprof") {
	case "cmdline":
		pprof.Cmdline(w, r)
	case "profile":
		pprof.Profile(w, r)
	case "symbol":
		pprof.Symbol(w, r)
	case "trace":
		pprof.Trace(w, r)
	default:
		Index(w, r)
	}
}
```

**Comment by husobee** [comment]
@josephspurrier: Thanks for the words of support. I have added the pprof example to the readme for others to benefit.  Thanks for the suggestion. Please feel free to close this issue.

**Comment by josephspurrier** [comment]
Wonderful! Thanks.
