### ISSUE TITLE
Routing bug with params and static routes

### ISSUE THREAD

**Issue by ernestoalejo** [husobee/vestigo#29]
I think I've hitted another unexpected artifact of #21 and #8.

```go
package main

import (
    "net/http"
    "log"
    "fmt"

    "github.com/husobee/vestigo"
)

func main() {
    router := vestigo.NewRouter()

	router.Get("/health", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintln(w, "health")})
	router.Get("/_/accounts/foo", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintln(w, "not param")})
	router.Get("/_/:project/bar", func(w http.ResponseWriter, r *http.Request) { fmt.Fprintln(w, "param")})
	log.Fatal(http.ListenAndServe(":10000", router))
}
```

```shell
$ curl localhost:10000/_/a/bar
Not Found

$ curl localhost:10000/_/b/bar
param

$ curl localhost:10000/_/abcd/bar
Not Found

$ curl localhost:10000/_/bcd/bar
param
```

`/health` route seems unrelated, but you need all three routes to trigger the bug.

**Comment by husobee** [comment]
Well, this has been a pesky bug :) I have put together a PR: https://github.com/husobee/vestigo/pull/33 which I hope completely resolves this issue.  I used the tests from https://github.com/husobee/vestigo/pull/30 which were previously failing, and now they pass.  @ernestoalejo: if you would be so kind as to try my "issue29fix" branch to see if this is a suitable solution I would appreciate it!

Thanks all for the work isolating this problem.

**Comment by ernestoalejo** [comment]
The branch seems to have fixed the issue both in the test code (as expected, it is now in your tests) and the real code that triggered it in the first place.
