### ISSUE TITLE
Are we escaping parameters correctly?

### ISSUE THREAD

**Issue by ernestoalejo** [husobee/vestigo#34]
I saw in the `pat` code they are escaping the parameters when storing them in the query string:
https://github.com/gorilla/pat/blob/master/pat.go#L99

We should probably do the same here:
https://github.com/husobee/vestigo/blob/master/common.go#L44

**Comment by husobee** [comment]
I purposely left out the url encoding from the url params because that operation is expensive and I felt the url params would be fairly safe as they are.  I would be up for adding a configuration method to perform url encoding if that would be of interest.

**Comment by josephspurrier** [comment]
I'd error on the side of don't trust user input since it is an exposed function. If someone types in a value with a space, it needs to be encoded properly. I submitted a pull request for this fix.

**Comment by josephspurrier** [comment]
Resolved with PR: https://github.com/husobee/vestigo/pull/36
