### ISSUE TITLE
301 redirect when route ends with slash

### ISSUE THREAD

**Issue by pete911** [husobee/vestigo#38]
It would be nice (if possible) to issue 301 redirect if path ends with forward slash. For example with this router: `router.Get("/test", testHandler)` request to `/test/` results in `404`, but it would be nicer if the response code was `301` with path to `/test`

**Comment by husobee** [comment]
I would be up for having a function, such as `vestigo.RedirectTrailingSlash()` where users can opt in.  I have had trouble with gorilla mux in the past with the trailing slash option they have being confusing.  If you want the same handler being called for trailing slash/non trailing slash you could add a function like this to your code:

```
func TrailingSlashOrNot(method, urlTemplate string, f http.HandlerFunc) {
    vestigo.Add(method, urlTemplate, f)
    vestigo.Add(method, utlTemplate+"/", f)
}
```
In my experience this type of thing gets very confusing, as many times the "/" at the end has a completely different meaning in an API, as it is usually a different resource.

Would love to hear more about this.

**Comment by pete911** [comment]
I was thinking of having something like this:

| router | request | response   |
|--------|---------|------------|
| /test  | /test   | 200        |
|        | /test/  | 301 /test  |

| router | request | response   |
|--------|---------|------------|
| /test/ | /test   | 301 /test/ |
|        | /test/  | 200        |

| router | request | response   |
|--------|---------|------------|
| /test  | /test   | 200        |
| /test/ | /test/  | 200        |

so the redirect would only happen if the difference is only in the ending slash. Of course it would make sense (as you pointed out) to make configurable, something like `defaultRedirect = true`

I don't think that it would be confusing, even default go http package uses redirects - https://golang.org/pkg/net/http/#ServeMux But this is just my view/opinion.

**Comment by slotheroo** [comment]
Seems like this would work well as an option that could be applied to the router itself at the user's discretion.
