### ISSUE TITLE
Routing "hangs" without wildcard

### ISSUE THREAD

**Issue by anihex** [husobee/vestigo#51]
Well ... I broke it again ... :sweat_smile: 

I got curious for a sec and tried this:

```go
package main

import (
	"fmt"
	"net/http"

	"github.com/husobee/vestigo"
)

func main() {
	router := vestigo.NewRouter()

	router.Get("/", ServeIndex)

	router.Get("/users/:name", UserShow)

	router.Get("/admin/", AdminIndex)

	router.Get("/books/", BookIndex)
	router.Get("/books/:book", BookShow)

	http.ListenAndServe(":8080", router)
}

func ServeIndex(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "root")
}

func BookIndex(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "bookindex")
}

func BookShow(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "book %s\n", vestigo.Param(r, "book"))
}

func UserShow(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "user %s\n", vestigo.Param(r, "name"))
}

func AdminIndex(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintln(w, "admin")
}
```

It turns out, it doesn't work so well. /users/ "hangs" instead of 404.

|Request|Result|Expected?|
|---|---|---|
|/|root|Yes|
|/somethings|Not Found|Yes|
|/books|Not Found|Yes|
|/books/|bookindex|Yes|
|/books/sonea|book sonea|Yes|
|/users|Not Found|Yes|
|/users/|[HANGS]|No (Expected: Not Found)|
|/users/chris|user chris|Yes|
|/admin|Not Found|Yes|
|/admin/|admin|Yes|
|/admin/chris|Not Found|Yes|

Sorry to bother you yet again. But I realy like this router. And since I can't realy help with the source, I'd at least want to help by testing it as much as I can. :innocent: 
And just by the way: This is not a deal breaker. If one knows of this, it's easily catchable.

At least I try to deliver a more test-friendly result in the response now ...

**Comment by husobee** [comment]
https://github.com/husobee/vestigo/pull/52 should fix it if you want to try it out. This was introduced in https://github.com/husobee/vestigo/pull/51

**Comment by anihex** [comment]
Fix #52 confirmed.

**Comment by husobee** [comment]
by all means, will leave this open, but i merged the PR.

**Comment by beehulinden** [comment]
@anihex: Find any more problems with the wildcard routing?  Thanks again for the help!

**Comment by husobee** [comment]
@anihex: have you found any more routing inconsistencies in your experiments?  Can we close this?

**Comment by anihex** [comment]
I didn't find any more inconsistencies in the routing. So yeah, I guess this can be closed.
