### ISSUE TITLE
route wildcard * has bug

### ISSUE THREAD

**Issue by xkeyideal** [husobee/vestigo#56]
example:
/books/:book
/books/*

**Comment by husobee** [comment]
The router is acting correctly, in my opinion, as it is taking an order or precedence with regards to url parameter matching versus wildcard matching.  The order of matching is:

1.) exact match
2.) match with url parameters
3.) match with wildcard at the end of the route

There is no way to tell from the router's stand point that the correct route is the route with the wildcard, versus the URL parameter, based on your example routes.

Here is a sample which, when run shows that the route with the url parameter at the end is matched:

```go
r := NewRouter()

r.Get("/books/:book", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "/books/%s\n", Param(r, "book"))
})

r.HandleFunc("/books/*", func(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "wildcard!! %s\n", Param(r, "_name"))
})

req, _ := http.NewRequest("GET", "/books/sdsd", nil)
w := httptest.NewRecorder()
r.ServeHTTP(w, req)
assert.True(t, strings.Contains(w.Body.String(), "/books/"))

```

As you can see from this example, no matter what you put as the url (not including '/*') you can expect to see the url parameter route being triggered.

Let me know if there is a better way than setting a defined order of precedence.

Thanks!
