### ISSUE TITLE
handlers.go imports net/http/httptest

### ISSUE THREAD

**Issue by antoooon** [husobee/vestigo#57]
When importing vestigo, it will implicitly import the "net/http/httptest" module.
This has the side-effect of adding "httptest.serve" command line argument, which is also printed to the usage description text (e.g. when using "--help"). 

Perhaps the functionality of httptest.ResponseRecorder can be implemented locally, to avoid this dependency on a testing module?

**Comment by husobee** [comment]
@antoooon: created a PR with the suggested change.  Thanks for catching this.  https://github.com/husobee/vestigo/pull/58  If you would, please code review this and I will get it merged in.

**Comment by antoooon** [comment]
Tested it, seems to work fine.
