### ISSUE TITLE
Vestigo's equivalent of gorilla/mux's PathPrefix

### ISSUE THREAD

**Issue by peteryates** [husobee/vestigo#62]
This isn't a bug but I can't find any information on it in the docs and I imagine it's a fairly-common use case. I'm using Vestigo in conjunction with Negroni and want to run certain middleware for 'protected' routes (those that start with `/api/`) but not others.

In `gorilla/mux` it'd be something along the lines of this:

```go
router := mux.NewRouter()
apiRoutes := mux.NewRouter()

router.PathPrefix("/api").Handler(negroni.New(
  SomeAuthMiddleware,
  negroni.Wrap(apiRoutes),
))
```

I can't see anything that resembles `PathPrefix` in Vestigo. What's the most sensible method for me to do this in Vestigo? Not looking for it to be spelled out for me, just a prod in the right direction!

**Comment by husobee** [comment]
Would something like this work for you:

```go
        // create a top level router
        routes := vestigo.NewRouter()
        // create api routes which will be protected with middleware
        apiRoutes := vestigo.NewRouter()
        // test routes which will NOT be protected with middleware
        testRoutes := vestigo.NewRouter()
        // end route for /api/example in the api router
        apiRoutes.Get("/api/example", GetExampleHandler)
        // end route for /test/example in test router
        testRoutes.Get("/test/example", GetExampleHandler)

        // wildcard route for /api/ which has negroni middlewares
        routes.Handle("/api/*", negroni.New(
                SomeAuthMiddleware,
                negroni.Wrap(apiRoutes),
        ))
        // wildcard route for /test/ which has no middlewares
        routes.Handle("/test/*", testRoutes)
        // both subrouters are now in top level router, so listen and serve routes
        log.Fatal(http.ListenAndServe(":8080", routes))
```

This obviously could be improved in the router itself, but that is how I would do something like that.  Let me know if that helps.  I am not opposed to adding a route prefix type scheme formally in the router.

**Comment by peteryates** [comment]
Ah, that looks promising. I'll give it a shot in the morning. 

Thanks for the quick response.

**Comment by husobee** [comment]
No problem!  I tested it out briefly and it seems to act as expected.

**Comment by peteryates** [comment]
Worked like a charm, thanks for that!
