### ISSUE TITLE
interceptors

### ISSUE THREAD

**Issue by pete911** [husobee/vestigo#67]
would you be interested in adding interceptors? We already have the code that extends current router, so can create pull request. The idea is to add vargs interceptor to existing methods:
```
router.Get("/path", someHandler, interceptor1, interceptor2)
// method signature
router.Get(path string, handler http.HandlerFunc, interceptors... Intercetpr)
router.Post(...)
...
```
interceptors are varagrs, so it wouldn't break existing code

**Comment by pete911** [comment]
I thought that it would be just easier to create pull request to illustrate this - https://github.com/husobee/vestigo/pull/68

**Comment by husobee** [comment]
Good idea @pete911, looking at it.

**Comment by pete911** [comment]
nice, let me know, I will add tests, update comments etc. if you are happy with the change
