### ISSUE TITLE
interceptor

### ISSUE THREAD

**Issue by pete911** [husobee/vestigo#69]
Hi, we just realised that the interceptor is not working properly. Basically in the intercept method you don't know if you are called after, or before the handler (if you return true from both methods). It would make more sense to change the interface to:

```
type Interceptor interface {
    Before(w http.ResponseWriter, r *http.Request) bool
    After(w http.ResponseWriter, r *http.Request) bool
}
```

the only problem is that it is going to break backward compatibility, is that ok?

**Comment by husobee** [comment]
@pete911:  I have to ask why do you need to know if you are before or after?  Why can't your implementation of Before() bool or After() bool set a flag in your structure so you will know in Intercept if it was before or after?

Personally, if I were to redo this functionality, I would look at something like this:  https://husobee.github.io/golang/http/middleware/2015/12/22/simple-middleware.html and use function closures to handle the before/after logic for your interceptor.  We could make a "middleware" function type that is passed into the route add function veridically and then just chain up handler functions.

As for the change, I feel like this functionality is so new, we are probably safe to change the behaviour.  Your thoughts?

**Comment by pete911** [comment]
I don't think that the flag would work, interceptor is shared by all the incoming requests, so they would be changing each others flags.

I am looking at the middleware function and it looks even better than having interface with before and after.

**Comment by pete911** [comment]
I have created pull request, have a look (it's just copy of your blog post) if you are happy with it.

**Comment by husobee** [comment]
@pete911: I merged https://github.com/husobee/vestigo/pull/70.  Thanks for taking lead on this new feature!
