### ISSUE TITLE
Fall-through route

### ISSUE THREAD

**Issue by fuzzybear3965** [husobee/vestigo#72]
I couldn't find this in the documentation or in the issues, so I prematurely apologize if this is a duplicate.
I want a default GET route that is matched in the event that no other route is matched by the router. I have something like this right now.
```
r.Get("/:domain/:user/:repo", getHandler(db))
// serve asset files
r.Get("/assets/*", http.StripPrefix("/assets/", http.FileServer(http.Dir("assets"))).ServeHTTP)
// serve built files
r.Get("/builds/*", http.StripPrefix("/builds/", http.FileServer(http.Dir("builds")))ServeHTTP)
// catch-all?
r.Get("/*", indexHandler)
```
However, the path `/somepath` doesn't get caught by the catch-all. However, `/somepath/` seems to get caught. Also, `/some/path` and `/some/path/` fail (but in different ways). `/some/path/` doesn't return a response (`net::ERR_EMPTY_RESPONSE` in Chrome dev tools) and `/some/path` returns a 404.

**Comment by husobee** [comment]
@fuzzybear3965:  I would suggest overwriting the default "Not Found" handler instead of doing the global wildcard route personally.  Example below:

```go
vestigo.CustomNotFoundHandlerFunc(indexHandler)
```

Would that work for your particular use case?

**Comment by fuzzybear3965** [comment]
That was perfect! Thanks, @husobee.
