### ISSUE TITLE
Middleware - HandlerFunc instead of Handler?oO

### ISSUE THREAD

**Issue by inzanez** [husobee/vestigo#77]
Hi

I might be doing something awfully wrong, but I usually wrote my middleware using something like:
```
func MiddleWare(next http.Handler) http.Handler {
  return http.Handlerfunc(func(w http.ResponseWriter, r *http.Request) {
    ...
    next.ServeHTTP(w, r)
    ...
  })
}
```
Somehow Vestigos middleware type doesn't seem to like that. Why does it only accept 'http.HandlerFunc' instead of both 'http.HandlerFunc' and 'http.Handler' as usual?

I just get:

> command-line-arguments
> ./routes.go:21:7: cannot use TestMiddle (type func(http.Handler) http.Handler) as type vestigo.Middleware in assignment

Well, again,...maybe I made a mistake somewhere along the path.

Best regards

**Comment by husobee** [comment]
Yes, the package only accepts middleware functions that take and return a `http.HandlerFunc` currently.  This is primarily due to the fact that the `Handle` functions all work with `http.HandlerFunc` parameters, example below:
```
// Get - Helper method to add HTTP GET Method to router
func (r *Router) Get(path string, handler http.HandlerFunc, middleware ...Middleware) {
	r.Add(http.MethodGet, path, handler, middleware...)
}
```
By having the middleware function type use `http.HandlerFunc` types it makes the processing of the middlewares easier to implement:

```
func buildChain(f http.HandlerFunc, m ...Middleware) http.HandlerFunc {

	// if our chain is done, use the original handlerfunc
	if len(m) == 0 {
		return f
	}
	// otherwise nest the handlerfuncs
	return m[0](buildChain(f, m[1:cap(m)]...))
}
```
I would be open to adding Handler support to the middlewares.  What is the reason though, to be able to access the handler struct instance from within the middleware?  Could something like that be achieved using the request context to pass the data/struct you need into the middlewares?

Thanks!

**Comment by hrvylein** [comment]
@husobee could you show me how to implement an HandlerFunc for returning (interface{}, error) to generate json output in a seperate jsonMiddleware?
I can't figure out how to wrap that in a HandlerFunc ...

**Comment by husobee** [comment]
Sure!  I think the best way to go about this is to use the request context to pass this response data to a "response middleware" which will perform the write of the response at the end of the middleware chain.  Check this out as an example:  https://github.com/husobee/suggest/blob/master/middleware/middleware.go#L88-L139

Basically it takes from the context the status code, and response payload and renders it.  This way in your other wrapped middlewares/handler you can update the request context before you return from the handler, and at the end of the middleware chain the response middleware will take that result and render.

Hope that helps!

**Comment by hrvylein** [comment]
Thanks for your reply. If I get that sample right, i'd have to set the error code in my routehandler and set a context variable to generate my json output. But wouldn't that lead to repeated code like if err != nil { /*set response code*/ }?

I thought it may be possible to do a "return returnVar, errorVar" and then let the jsonHandler generate the output.
If this isn't possible, how do you update the responsecode without repeating code over and over?

**Comment by husobee** [comment]
In my handlers I use a helper, like this:  https://github.com/husobee/suggest/blob/master/handlers/handlers.go#L28-L29

Here is the definition of the helper:  https://github.com/husobee/suggest/blob/master/handlers/handlers.go#L43-L47

Hope that example helps!
