### ISSUE TITLE
Add new Release for go native vendoring

### ISSUE THREAD

**Issue by monomosc** [husobee/vestigo#78]
## Issue

When using the almost official [Dep - Tool](https://github.com/golang/dep) it automatically configures itself to use the latest Release of Dependencies. For Vestigo this is v1.0.2 and it doesn't support passing Middleware in Methods like 
```Go
router.Get("/example", exampleHandler, middlewares...)
```

## Current Solution

I now manually edit the Gopkg.toml file to set dependecy to vestigo to a specific revision (sha1-commit). This is obviously not ideal. I am also thinking of forking, but that seems massively eccessive.

## Proposal

Add a new Release (v1.1.0) to vestigo. That will allow users of dep and vestigo  to set their gobpkg.toml to that release and higher.

**Comment by husobee** [comment]
Thank you for pointing this out.  I added the v1.1.0 tag as suggested and pointed it to the latest commit.  Please let me know if there are further issues.

**Comment by monomosc** [comment]
Thanks alot!
